# Generated by Django 4.0.3 on 2022-04-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cigarette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_sales', models.CharField(default=0, max_length=100)),
                ('product_purchases', models.CharField(default=0, max_length=100)),
                ('product_stock_on_hand', models.CharField(default=0, max_length=100)),
                ('stock_level', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
